{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "certcenter.fullname" . }}
  labels:
    {{- include "certcenter.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.toml: |
    {{- include "certcenter.configToml" . | nindent 4 }}
{{- end }}
